USE employeedirectory;
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
create table assignments (client_id integer, id integer not null auto_increment, assignment_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table client (clientid integer not null, phone_number integer, email_address varchar(255), first_name varchar(255), last_name varchar(255), primary key (clientid)) engine=InnoDB;
create table department (departmentid integer not null, max_employees integer, specialization varchar(255), primary key (departmentid)) engine=InnoDB;
create table employee (departmentid integer, employeeid integer not null, is_full_time bit, is_leader bit, is_part_time bit, phone_number integer, dtype varchar(31) not null, email_address varchar(255), first_name varchar(255), last_name varchar(255), type varchar(255), primary key (employeeid)) engine=InnoDB;
create table employee_project (assignmentid integer, employeeid integer not null, projectid integer not null, primary key (employeeid, projectid)) engine=InnoDB;
create table employee_skill (employeeid integer not null, skill_level integer, skillid integer not null, primary key (employeeid, skillid)) engine=InnoDB;
create table meetings (departmentid integer, meetingid integer not null, end_date datetime(6), start_date datetime(6), location varchar(255), meeting_type varchar(255), title varchar(255), primary key (meetingid)) engine=InnoDB;
create table meetings_employee (employeeid integer not null, meetingid integer not null, attendance_status varchar(255), primary key (employeeid, meetingid)) engine=InnoDB;
create table project (clientid integer, departmentid integer, projectid integer not null, end_date datetime(6), start_date datetime(6), meeting_type varchar(255), project_name varchar(255), status varchar(255), primary key (projectid)) engine=InnoDB;
create table project_costs (amount decimal(38,2), costid integer not null, projectid integer, due_date datetime(6), description varchar(255), expense_type varchar(255), primary key (costid)) engine=InnoDB;
create table project_milestones (milestoneid integer not null, projectid integer, description varchar(255), milestone_name varchar(255), primary key (milestoneid)) engine=InnoDB;
create table skill (skillid integer not null, description varchar(255), skill_name varchar(255), primary key (skillid)) engine=InnoDB;
alter table employee_project add constraint UK_lvkkufcjom6oe6mnrw92exym4 unique (assignmentid);
alter table assignments add constraint FKfuok6ahc8bn31u85lp3aotrfj foreign key (client_id) references client (clientid);
alter table employee add constraint FKpqnkyknoe4bmsfhnwdfaans5r foreign key (departmentid) references department (departmentid);
alter table employee_project add constraint FKr2ytarre3y6g3euqw3hsuiu6e foreign key (employeeid) references employee (employeeid);
alter table employee_project add constraint FKc89e4locumunhon3jkwyesrb9 foreign key (projectid) references project (projectid);
alter table employee_project add constraint FKamx3mr85md07iu37sy4iim3v9 foreign key (assignmentid) references assignments (id);
alter table employee_skill add constraint FK9r6s98d2ad6bmcnt5lvbl551p foreign key (employeeid) references employee (employeeid);
alter table employee_skill add constraint FKo46q716jpkfqcdvkoh0purnff foreign key (skillid) references skill (skillid);
alter table meetings add constraint FK38b9q7pil7nt5pnpo3ntdhxav foreign key (departmentid) references department (departmentid);
alter table meetings_employee add constraint FKbcuw4v7xnkxys5eawh8hm21wp foreign key (employeeid) references employee (employeeid);
alter table meetings_employee add constraint FK9y6brud2cudqov2ptq4au1wou foreign key (meetingid) references meetings (meetingid);
alter table project add constraint FKi6mikgf1ffvc446f1f6ks7mn1 foreign key (clientid) references client (clientid);
alter table project add constraint FKgpik1em37r29wrfvj6go5aorm foreign key (departmentid) references department (departmentid);
alter table project_costs add constraint FK744oemvlmen9oto3pfh9mu543 foreign key (projectid) references project (projectid);
alter table project_milestones add constraint FKihu7npm6x97ka7wv8f5fsu4t2 foreign key (projectid) references project (projectid);
