# Data Source Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedirectory?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: Stupy_Mihai
    driverClassName: com.mysql.cj.jdbc.Driver


  # JPA Configuration
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      javax.persistence.schema-generation.create-source: metadata
      javax.persistence.schema-generation.drop-source: metadata
      javax.persistence.schema-generation.scripts.action: create
      javax.persistence.schema-generation.scripts.create-target: create.sql
      javax.persistence.schema-generation.scripts.create-source: metadata
