# Data Source Configuration
spring:
  datasource:
    url: jdbc:h2:mem:EmployeeDirectory
    username: Stupy
    password: Mihai
    driverClassName: org.h2.Driver


  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
debug: false
